- name : Declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variale
      ansible.builtin.debug:
        msg: URL = {{URL}}
